#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yuya Kyama
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math

ans = 0
for line in sys.stdin:
    try:
        print(math.sin(math.radians(int(line))))
    except:
        print(math.sin(math.radians(float(line))))
